language: android
      
android:
  components:
  - tools
  - build-tools-25.0.0
  - android-25
  - extra
  - add-on

  licenses:
  - 'android-sdk-license.*'

jdk:
  - oraclejdk8

script:
   - ./gradlew build connectedCheck