language: android

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      
android:
  components:
  - tools
  - build-tools-25.0.0
  - android-25
  - extra
  - add-on

  licenses:
  - 'android-sdk-license.*'

script:
   - ./gradlew build connectedCheck