language: android

env:
  global:
    - ANDROID_API_LEVEL=25
    - EMULATOR_API_LEVEL=22
    - ANDROID_BUILD_TOOLS_VERSION=25.0.0
    - ANDROID_ABI=google_apis/armeabi-v7a
      
android:
  components:
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - extra
  - add-on
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL

  licenses:
  - 'android-sdk-license.*'

jdk:
  - oraclejdk8
  
before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:"$EMULATOR_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator

script:
   - ./gradlew build connectedCheck